apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy-service-account
  namespace: pi
  labels:
    app: proxy
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: pi
  labels:
    app: proxy
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: proxy
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: pi
  labels:
    app: proxy
    version: "2002"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
      version: "2002"
  template:
    metadata:
      labels:
        app: proxy
        version: "2002"
    spec:
      serviceAccountName: proxy-service-account
      containers:
        - image: nginx:1.17.8-alpine
          name: nginx
          resources:
            limits:
              cpu: 250m
              memory: 500Mi
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: config
              mountPath: "/etc/nginx/"
              readOnly: true
            - name: cache-volume
              mountPath: /data/nginx/cache
      volumes:
        - name: config
          configMap:
            name: nginx-configmap
        - name: cache-volume
          emptyDir: {}
